[package]
name = "shed"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A command-line tool"
license = "MIT"
readme = "README.md"
publish = false

[dependencies]

[lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
dbg_macro = "deny"
todo = "deny"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
